### ISSUE TITLE
Current way of setting params seems not working

### ISSUE THREAD

**Issue by nguyenlamlll** [Rhetos/RhetosCli#8]
With the current method, `cmd` indeed has the parameters specified in `command`. 
https://github.com/Rhetos/RhetosCli/blob/3465d0ae8dc7bdd1939de9b98dad8d815d694384/RhetosCLI/Program.cs#L31

But when I try to call `rhetoscli release get rhetosVersion=latest`, it throws:
```
2018-10-18 09:49:01.8587 Fatal  System.Reflection.TargetParameterCountException: Parameter count mismatch.
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at RhetosCLI.Program.Main(String[] args) in D:\Lam\REAL PROJECTS\RhetosCli\RhetosCLI\Program.cs:line 33
```

https://github.com/Rhetos/RhetosCli/blob/3465d0ae8dc7bdd1939de9b98dad8d815d694384/RhetosCLI/Program.cs#L33
^ Invoke doesn't pass the parameter from `cmd` to the method V
```
public string DownloadRhetosRelease(string version) { }
```
,hence the mismatch.

----
I'm currently implementing a way to pass all parameters to `Invoke` method, proposed like this:
```
object[] parametersArray = command.Parameters.Values.ToArray();
methodInfo.Invoke(cmd, parametersArray);
```
However, there is still a problem with this approach. Image we have a `CliCommand` prototype as `public void DoSomething(string param-a, string param-b)` and the user supposedly calls `rhetoscli module doSomething param-a=A param-B=B`. This works. However, `rhetoscli module doSomething param-B=B param-a=A ` **won't** work as intended.

Parameters should be position-independent. :( In the meantime, I'll try to match the params from users with the positions required in `CliCommand` methods.

**Comment by VladimirZD** [comment]
I know for this issue... Params order isn't issue. Issue is that i am not handling method parameters...
I am fixing this.
