### ISSUE TITLE
Missing required arguments check

### ISSUE THREAD

**Issue by jbasioli** [Rhetos/RhetosCli#9]
When RhetosCLI is called with incorrect number of arguments (e.g. 1) it returns exception and call stack. Arguments should be checked before resolving command and inform user of proper usage.

Exception:
```
PS C:\Source\Rhetos\RhetosCli\RhetosCLI\bin\Debug> .\RhetosCLI.exe release
2018-11-22 16:13:26.1784 Info Rhetos CLI version 0.0.0.28563
2018-11-22 16:13:26.2096 Fatal  System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at RhetosCLI.Helpers.MiscHelpers.ParseCommandLine(String[] args) in C:\Source\Rhetos\RhetosCli\RhetosCLI\Helpers\Helpers.cs:line 170
   at RhetosCLI.Program.Main(String[] args) in C:\Source\Rhetos\RhetosCli\RhetosCLI\Program.cs:line 19
```

**Comment by VladimirZD** [comment]
Working on that. It will show help in future..
While i fix it you can use 

RhetosCLI.exe Rhetos Create RhetosVersion=latest DBServer=yourserver DataBaseName=yourdatabase DBUserName="" DBPassword="" UseWindowsAuth=true AppName=vlado_test AppPoolName=vlado_test UserName=yourdomainusername Password=blabla

To create new app...
